volumes:
  local_postgres_data:

services:
  postgres:
    image: postgres:16
    container_name: local_postgres
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=betterstarter
