volumes:
  production_traefik: {}
  production_traefik_logs: {}
  production_crowdsec_data: {}
  production_crowdsec_config: {}

services:
  next-app:
    build:
      context: .
      dockerfile: ./compose/production/node/Dockerfile
    image: production_next_app
    command: node server.js
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    environment:
      - TZ: "UTC"
      - PGID: "1000"
      - COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve"
    expose:
      - "8080"
    volumes:
      - /var/log/crowdsec:/var/log/crowdsec:ro
      - /opt/crowdsec-db:/var/lib/crowdsec/data
      - /var/log/auth.log:/var/log/auth.log:ro
      - /opt/crowdsec:/etc/crowdsec
      - "./logsTraefik:/var/log/traefik"
    labels:
      traefik.enable: "false"

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: production_traefik
    depends_on:
      - next-app
      - crowdsec
    volumes:
      - production_traefik:/etc/traefik/acme
      - production_traefik_logs:/var/log/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - "./logsTraefik:/var/log/traefik"
    env_file:
      - ./.envs/.production/.traefik
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
